### PR TITLE
client.Populate assign client to proxy

### PR DESCRIPTION
**Pull request by hellodudu**
`client.Populate` should assign client to proxies first, otherwise it will panic if we call ``` proxy.AddToxic()```

### CODE REVIEW

**Comment by miry** [comment]
@hellodudu can you add tests to cover the panic?

**Comment by hellodudu** [comment]
Hi @miry, It's done.

**Comment by miry** [comment]
@hellodudu Thank you very much. Last steps:

1. Update Changelog.md with summary of your changes: next line after https://github.com/Shopify/toxiproxy/blob/master/CHANGELOG.md?plain=1#L5
2. There is small linting problem: extra empty line
3. Squash commits and rebase against master

**Comment by hellodudu** [comment]
@miry 

1. done.
2. done.
3. I haven't squash commit on Github before, always use the "confirm squash and merge" comes from Github. I'm worried about squashing with errors when using git. Do you have right to "confirm squash and merge"?

**Comment by miry** [comment]
@hellodudu It looks like: `git rebase -i HEAD~4` then you left first row uncahnged (check that it is your first commit), and all other change first word `patch` to `squash`.

In the end it would ask to provide description.

**Comment by miry** [comment]
@hellodudu If you want I can squash and try to combine your messages in one?

**Comment by hellodudu** [comment]
Yes please. I'm afraid of messing it up. Thanks a lot!

**Comment by miry** [comment]
@hellodudu thank you again for contribution  ❤️ . Going to update my samples of toxiproxy usage.

**Pull request merged**
