### PR TITLE
Bump Go versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
@jpittis Ping

**Comment by jpittis** [comment]
What's the point of this given Travis `1.x` is already running at the following version:

```
$ go version
go version go1.11.1 linux/amd64
```

**Comment by HaraldNordgren** [comment]
@jpittis I don't see that `1.x` was there. You are right, there is really no point. Closing this!

**Comment by jpittis** [comment]
Appreciate the PR either way Harald. Thanks!

**Pull request closed without merging**
